### ISSUE TITLE
ModuleNotFoundError: No module named 'yamlpath.patches'

### ISSUE THREAD

**Issue by masterphenix** [wwkimball/yamlpath#142]
## Operating System

1. Name/Distribution: Ubuntu (on WSL)
2. Version: 18.04.5 LTS

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions):
2. Python Version: 3.8.0
3. Version of yamlpath installed: 3.6.1
4. Version of ruamel.yaml installed: 0.16.12

## Minimum sample of YAML (or compatible) data necessary to trigger the issue
Any file will do, here is a simple one :
```
---
test:
  key1: value1
```

## Complete steps to reproduce the issue when triggered via:

yaml-get --query test.key test.yml

## Actual Outcome
```
Traceback (most recent call last):
  File "/home/sr/.local/bin/yaml-get", line 5, in <module>
    from yamlpath.commands.yaml_get import main
  File "/home/sr/.local/lib/python3.8/site-packages/yamlpath/__init__.py", line 6, in <module>
    from yamlpath.processor import Processor
  File "/home/sr/.local/lib/python3.8/site-packages/yamlpath/processor.py", line 18, in <module>
    from yamlpath.common import Anchors, KeywordSearches, Nodes, Searches
  File "/home/sr/.local/lib/python3.8/site-packages/yamlpath/common/__init__.py", line 4, in <module>
    from .parsers import Parsers
  File "/home/sr/.local/lib/python3.8/site-packages/yamlpath/common/parsers.py", line 25, in <module>
    from yamlpath.patches.aliasstyle import MySerializer # type: ignore
ModuleNotFoundError: No module named 'yamlpath.patches'
```

It seems that "patches" is not included in the release's zip or tar.gz assets.

**Comment by combolek** [comment]
I just found this and for anyone searching I wanted to add my Fedora 35 experience. Fedora 35 does not come with yamlpath so I installed it using pip and still got the above error. The problems was that Fedora does come with python3-ruamel-yaml-0.16.6 which was already installed on my machine. I had to remove the rpm package and add then reinstall yamlpath via pip (which pulls in the latest ruamel.yaml) to fix the error.
