### ISSUE TITLE
Importing yamlpath==3.6.6 raises ModuleNotFoundError('yamlpath.patches')

### ISSUE THREAD

**Issue by kaniblu** [wwkimball/yamlpath#185]
## Operating System

1. Name/Distribution: Ubuntu 
2. Version: 18.04.5 LTS (Bionic Beaver)

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): Anaconda
2. Python Version: 3.8.12
3. Version of yamlpath installed: 3.6.6
4. Version of ruamel.yaml installed: 0.17.21

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```python
import yamlpath
```

## Complete steps to reproduce the issue when triggered via:

```
conda create -y -n test python==3.8.12
conda activate test
pip install yamlpath==3.6.6
python -c "import yamlpath"
```

## Actual Outcome

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/__init__.py", line 5, in <module>
    from yamlpath.yamlpath import YAMLPath
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/yamlpath.py", line 9, in <module>
    from yamlpath.types import PathAttributes, PathSegment
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/types/__init__.py", line 3, in <module>
    from .pathattributes import PathAttributes
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/types/pathattributes.py", line 8, in <module>
    from yamlpath.path import CollectorTerms
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/path/__init__.py", line 2, in <module>
    from .collectorterms import CollectorTerms
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/path/collectorterms.py", line 6, in <module>
    from yamlpath.enums import CollectorOperators
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/enums/__init__.py", line 9, in <module>
    from .yamlvalueformats import YAMLValueFormats
  File "/home/kani/.conda3/lib/python3.8/site-packages/yamlpath/enums/yamlvalueformats.py", line 23, in <module>
    from yamlpath.patches.timestamp import (
ModuleNotFoundError: No module named 'yamlpath.patches'
```

**Comment by wwkimball** [comment]
The upcoming release for version 3.6.7 appears to include the missing patch file; this line showed up in the output of the package builder:

```text
  adding: yamlpath-3.6.7/yamlpath/patches/timestamp.py  (in=4569) (out=1509) (deflated 67%)
```

**Comment by wwkimball** [comment]
Please upgrade to version 3.6.7.
